import type { HindsightConfig } from "./config.js";

export function makeConfig(overrides: Partial<HindsightConfig> = {}): HindsightConfig {
  return {
    autoRecall: true,
    recallBudget: "mid",
    recallMaxTokens: 1024,
    recallTypes: ["observation"],
    recallContextTurns: 1,
    recallMaxQueryChars: 800,
    minRecallPromptChars: 5,
    recallPromptPreamble: "",
    recallTags: [],
    recallTagsMatch: "any",
    autoRetain: true,
    retainMode: "full-session",
    retainEveryNTurns: 10,
    retainOverlapTurns: 2,
    retainToolCalls: true,
    retainContext: "opencode",
    retainTags: [],
    retainMetadata: {},
    hindsightApiUrl: "https://api.hindsight.vectorize.io",
    hindsightApiToken: null,
    bankId: null,
    bankIdPrefix: "",
    dynamicBankId: true,
    dynamicBankGranularity: ["gitProject"],
    bankMission: "",
    retainMission: null,
    agentName: "opencode",
    debug: false,
    ...overrides,
  };
}
